# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-07 13:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='updated',
            new_name='updated_at',
        ),
    ]
